### ISSUE TITLE
FEAT: Lexer와 Parser 기능 구현

### ISSUE THREAD

**Issue by middlefitting** [middlefitting/Minishell#8]
## 세부사항
- readline의 입력값을 처리하기 위한 Lexer와 parser 기능을 구현합니다.
1. Lexer: readline의 입력값을 적절한 문자열 토큰으로 변환합니다
2. Parser: 문자열 토큰을 문법에 맞추어서 트리 자료구조에 저장합니다.

**Comment by JeisaNewbie** [comment]
LGTM! 고생하셨습니다 :)
